name: Deploy to App Store

on:
  push:
    branches:
      - 'main'
    paths:
      - 'app/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      IONIC_TOKEN: ${{ secrets.IONIC_TOKEN }}
      APP_ID: '352d161b'
      SIGNING_CERT: 'App Store'
      DESTINATION: 'AppStore'

    steps:
      - name: Install Appflow CLI
        run: curl -sL https://ionic.io/get-appflow-cli | bash

      - name: Build AAB and Save Android Build ID
        id: ios_build
        run: |
          IOS_BUILD_ID=$(appflow build ios app-store --app-id=$APP_ID --commit=$GITHUB_SHA --signing-cert="$SIGNING_CERT" --environment ".env" --json --token=$IONIC_TOKEN | jq -r ".buildId")
          echo "IOS_BUILD_ID=$IOS_BUILD_ID" >> $GITHUB_OUTPUT

      - name: Deploy to App Store
        run: appflow deploy ios --app-id=$APP_ID --build-id=${{ steps.ios_build.outputs.IOS_BUILD_ID }} --destination="$DESTINATION" --token=$IONIC_TOKEN
